@startuml auth

namespace com.example.ezvault.authentication.authentication {
    interface IAuthenticationStrategy {
        + authenticate(): Task<User>
    }

    abstract class FirebaseAuthenticationStrategy {
        # firebase: FirebaseBundle

        + {abstract} authenticateUser(): Task<AuthResult>
        + authenticate(): Task<User>

        + <<Create>> FirebaseAuthenticationStrategy(firebase: FirebaseBundle)
    }
    note left of FirebaseAuthenticationStrategy : Allows subclasses to solely\n focus on Firebase-based auth

    FirebaseAuthenticationStrategy .up.> IAuthenticationStrategy

    class EmailPasswordAuthenticationStrategy {
        - email: String
        - password: String

        + authenticateUser(): Task<AuthResult>
        + <<Create>> EmailPasswordAuthenticationStrategy(email: String, password: String)
    }
    note left of EmailPasswordAuthenticationStrategy : Uses firebase provided \n email & password auth
    EmailPasswordAuthenticationStrategy -up-|> FirebaseAuthenticationStrategy
}

@enduml