@startuml auth

namespace com.example.ezvault.authentication.registration {
    class EmailPasswordRegistrationStrategy {
        - email: String
        - password: String

        + authenticateUser(): Task<AuthResult>
        + <<Create>> EmailPasswordRegistrationStrategy(email: String, password: String)
    }
    note left of EmailPasswordRegistrationStrategy : Uses firebase provided \n email & password auth

    abstract class FirebaseRegistrationStrategy {
        # firebase: FirebaseBundle

        + {abstract} registerUser(): Task<AuthResult>
        + register(): Task<User>

        + <<Create>> FirebaseRegistrationStrategy(firebase: FirebaseBundle)
    }
    note left of FirebaseRegistrationStrategy : Allows subclasses to solely\n focus on Firebase-based auth

    interface IRegistrationStrategy {
        + register(): Task<User>
    }



    EmailPasswordRegistrationStrategy -up-|> FirebaseRegistrationStrategy
    FirebaseRegistrationStrategy .up.> IRegistrationStrategy
}

@enduml